/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lk.redwolfdynamic.ims.gui;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.CardLayout;
import javax.swing.SwingUtilities;
import lk.redwolfdynamic.ims.panel.AttendanceManagementPanel;
import lk.redwolfdynamic.ims.panel.DashboardPanel;
import lk.redwolfdynamic.ims.panel.ExamManagementPanel;
import lk.redwolfdynamic.ims.panel.FeeManagementPanel;
import lk.redwolfdynamic.ims.panel.StudentManagementPanel;
import lk.redwolfdynamic.ims.panel.CourceManagementPanel;
import lk.redwolfdynamic.ims.panel.TeacherManagementPanel;
import lk.redwolfdynamic.ims.panel.TimetableManagementPanel;

/**
 *
 * @author RedWolf
 */

/**
 * Creates new form Admin_Dashboard
 */

public class Receptions_Dashboard extends javax.swing.JFrame {

    private DashboardPanel dashboardPanel;
    private StudentManagementPanel studenManagementPanel;
    private AttendanceManagementPanel attendanceManagementPanel;
    private ExamManagementPanel examManagementPanel;
    private FeeManagementPanel feeManagementPanel;
    private CourceManagementPanel subjectManagementPanel;
    private TeacherManagementPanel teacherManagementPanel;
    private TimetableManagementPanel timetableManagementPanel;
    private CardLayout contentPanelLayout;


    public Receptions_Dashboard() {
        initComponents();
    }

    private void init() {
        sideBar.putClientProperty(FlatClientProperties.STYLE, "arc:15");
        mainPanel.putClientProperty(FlatClientProperties.STYLE, "arc:15");
    }

    private void loadPanels() {
        if (contentPanelLayout == null && contentPanel.getLayout() instanceof CardLayout) {
            this.contentPanelLayout = (CardLayout) contentPanel.getLayout();
        }
        //System.out.println(contentPanelLayout);
        this.dashboardPanel = new DashboardPanel();
        this.studenManagementPanel = new StudentManagementPanel();
        this.attendanceManagementPanel = new AttendanceManagementPanel();
        this.examManagementPanel = new ExamManagementPanel();
        this.feeManagementPanel = new FeeManagementPanel();
        this.subjectManagementPanel = new CourceManagementPanel();
        this.teacherManagementPanel = new TeacherManagementPanel();
        this.timetableManagementPanel = new TimetableManagementPanel();

        this.contentPanel.add(dashboardPanel, "dashboard_panel");
        this.contentPanel.add(studenManagementPanel, "studenManagement_panel");
        this.contentPanel.add(attendanceManagementPanel, "attendanceManagement_panel");
        this.contentPanel.add(examManagementPanel, "examManagement_panel");
        this.contentPanel.add(feeManagementPanel, "feeManagement_panel");
        this.contentPanel.add(subjectManagementPanel, "subjectManagement_panel");
        this.contentPanel.add(teacherManagementPanel, "teacherManagement_panel");
        this.contentPanel.add(timetableManagementPanel, "timetableManagement_panel");
        SwingUtilities.updateComponentTreeUI(contentPanel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sideBar = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        btn_studentManagement = new javax.swing.JButton();
        btn_teacherManagement = new javax.swing.JButton();
        btn_subjectManagement = new javax.swing.JButton();
        btn_attendanceManagement = new javax.swing.JButton();
        btn_feeManagement = new javax.swing.JButton();
        btn_timetableManagement = new javax.swing.JButton();
        btn_examManagement = new javax.swing.JButton();
        btn_dashboard = new javax.swing.JButton();
        btn_examManagement1 = new javax.swing.JButton();
        btn_settings1 = new javax.swing.JButton();
        mainPanel = new javax.swing.JScrollPane();
        contentPanel = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        uName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Receptions Dashboard");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lk/redwolfdynamic/ims/img/ismlogo64x.png"))); // NOI18N

        btn_studentManagement.setFont(new java.awt.Font("IBM Plex Sans Condensed", 0, 14)); // NOI18N
        btn_studentManagement.setText("Student Management");
        btn_studentManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_studentManagementActionPerformed(evt);
            }
        });

        btn_teacherManagement.setFont(new java.awt.Font("IBM Plex Sans Condensed", 0, 14)); // NOI18N
        btn_teacherManagement.setText("Teacher Management");
        btn_teacherManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_teacherManagementActionPerformed(evt);
            }
        });

        btn_subjectManagement.setFont(new java.awt.Font("IBM Plex Sans Condensed", 0, 14)); // NOI18N
        btn_subjectManagement.setText("Subject Management");
        btn_subjectManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_subjectManagementActionPerformed(evt);
            }
        });

        btn_attendanceManagement.setFont(new java.awt.Font("IBM Plex Sans Condensed", 0, 14)); // NOI18N
        btn_attendanceManagement.setText("Attendance Management");
        btn_attendanceManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_attendanceManagementActionPerformed(evt);
            }
        });

        btn_feeManagement.setFont(new java.awt.Font("IBM Plex Sans Condensed", 0, 14)); // NOI18N
        btn_feeManagement.setText("Fee Management");
        btn_feeManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_feeManagementActionPerformed(evt);
            }
        });

        btn_timetableManagement.setFont(new java.awt.Font("IBM Plex Sans Condensed", 0, 14)); // NOI18N
        btn_timetableManagement.setText("Timetable Management");
        btn_timetableManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timetableManagementActionPerformed(evt);
            }
        });

        btn_examManagement.setFont(new java.awt.Font("IBM Plex Sans Condensed", 0, 14)); // NOI18N
        btn_examManagement.setText("Exam Management");
        btn_examManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_examManagementActionPerformed(evt);
            }
        });

        btn_dashboard.setFont(new java.awt.Font("IBM Plex Sans Condensed", 0, 14)); // NOI18N
        btn_dashboard.setText("Dashboard");
        btn_dashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dashboardActionPerformed(evt);
            }
        });

        btn_examManagement1.setFont(new java.awt.Font("IBM Plex Sans Condensed", 0, 14)); // NOI18N
        btn_examManagement1.setText("Exam Results");
        btn_examManagement1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_examManagement1ActionPerformed(evt);
            }
        });

        btn_settings1.setFont(new java.awt.Font("IBM Plex Sans Condensed", 0, 14)); // NOI18N
        btn_settings1.setText("Reports");
        btn_settings1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_settings1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sideBarLayout = new javax.swing.GroupLayout(sideBar);
        sideBar.setLayout(sideBarLayout);
        sideBarLayout.setHorizontalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addGroup(sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_studentManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_teacherManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_subjectManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_attendanceManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_feeManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_timetableManagement, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_examManagement, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_examManagement1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_settings1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(sideBarLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(logo)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        sideBarLayout.setVerticalGroup(
            sideBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logo)
                .addGap(18, 18, 18)
                .addComponent(btn_dashboard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_studentManagement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_teacherManagement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_subjectManagement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_attendanceManagement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_feeManagement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_timetableManagement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_examManagement)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_examManagement1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_settings1)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        mainPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        mainPanel.setFont(new java.awt.Font("IBM Plex Sans Condensed", 0, 14)); // NOI18N

        contentPanel.setLayout(new java.awt.CardLayout());
        mainPanel.setViewportView(contentPanel);

        name.setFont(new java.awt.Font("IBM Plex Sans Condensed", 0, 14)); // NOI18N
        name.setText("Name");
        name.setOpaque(true);

        uName.setFont(new java.awt.Font("IBM Plex Sans Condensed", 0, 12)); // NOI18N
        uName.setText("username");
        uName.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sideBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 950, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(uName, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sideBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainPanel)
                .addGap(7, 7, 7))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_studentManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_studentManagementActionPerformed
        this.contentPanelLayout.show(contentPanel, "studenManagement_panel");
    }//GEN-LAST:event_btn_studentManagementActionPerformed

    private void btn_teacherManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_teacherManagementActionPerformed
        this.contentPanelLayout.show(contentPanel, "teacherManagement_panel");
    }//GEN-LAST:event_btn_teacherManagementActionPerformed

    private void btn_subjectManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_subjectManagementActionPerformed
        this.contentPanelLayout.show(contentPanel, "subjectManagement_panel");
    }//GEN-LAST:event_btn_subjectManagementActionPerformed

    private void btn_attendanceManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_attendanceManagementActionPerformed
        this.contentPanelLayout.show(contentPanel, "attendanceManagement_panel");
    }//GEN-LAST:event_btn_attendanceManagementActionPerformed

    private void btn_feeManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_feeManagementActionPerformed
        this.contentPanelLayout.show(contentPanel, "feeManagement_panel");
    }//GEN-LAST:event_btn_feeManagementActionPerformed

    private void btn_timetableManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timetableManagementActionPerformed
        this.contentPanelLayout.show(contentPanel, "timetableManagement_panel");
    }//GEN-LAST:event_btn_timetableManagementActionPerformed

    private void btn_examManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_examManagementActionPerformed
        this.contentPanelLayout.show(contentPanel, "examManagement_panel");
    }//GEN-LAST:event_btn_examManagementActionPerformed

    private void btn_dashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dashboardActionPerformed
        this.contentPanelLayout.show(contentPanel, "dashboard_panel");
    }//GEN-LAST:event_btn_dashboardActionPerformed

    private void btn_examManagement1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_examManagement1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_examManagement1ActionPerformed

    private void btn_settings1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_settings1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_settings1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        FlatDarkLaf.setup();

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receptions_Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_attendanceManagement;
    private javax.swing.JButton btn_dashboard;
    private javax.swing.JButton btn_examManagement;
    private javax.swing.JButton btn_examManagement1;
    private javax.swing.JButton btn_feeManagement;
    private javax.swing.JButton btn_settings1;
    private javax.swing.JButton btn_studentManagement;
    private javax.swing.JButton btn_subjectManagement;
    private javax.swing.JButton btn_teacherManagement;
    private javax.swing.JButton btn_timetableManagement;
    private javax.swing.JPanel contentPanel;
    private javax.swing.JLabel logo;
    private javax.swing.JScrollPane mainPanel;
    private javax.swing.JLabel name;
    private javax.swing.JPanel sideBar;
    private javax.swing.JLabel uName;
    // End of variables declaration//GEN-END:variables
}
